- name: Install packages
  become: true
  community.general.pacman:
    name:
      - awesome-terminal-fonts
      - ttf-font-awesome
      - ttf-dejavu
      - ttf-droid
      - ttf-nerd-fonts-symbols-common
      - ttf-roboto-mono
      - noto-fonts-cjk
      - noto-fonts-emoji

# This because of extensive use of the --print-format :
# https://docs.ansible.com/ansible/latest/collections/community/general/pacman_module.html#parameter-executable
- name: Install ttf-ubraille AUR packages
  ansible.builtin.command: paru -Syu --noconfirm --nouseask ttf-ubraille
  args:
    creates: /usr/share/fonts/TTF/UBraille.ttf

- name: Create fontconfig directory
  ansible.builtin.file:
    path: ~/.config/fontconfig/
    state: directory
    mode: '755'

- name: Copy fonts.conf
  ansible.builtin.copy:
    src: fonts.conf
    dest: ~/.config/fontconfig/fonts.conf
    mode: '644'
